[versions]
shadow = "8.1.1"
delombok = "8.4"

fulmicollection = "1.3.8"

spigot = "1.13-R0.1-SNAPSHOT"

lombok = "1.18.30"
annotations = "24.1.0"
junit = "5.9.1"

[libraries]
fulmicollection = { module = "it.fulminazzo:FulmiCollection", version.ref = "fulmicollection" }

spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
annotations = { module = "org.jetbrains:annotations", version.ref = "annotations" }
junit-platform = { module = "org.junit:junit-bom", version.ref = "junit" }