# 1.19.4-R0.1-SNAPSHOT
name: MC 1.19

on:
  push:
    branches: [ "main", "master", "dev" ]

jobs:
  test:
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 17
      minecraft-version: "1.19.4-R0.1-SNAPSHOT"