# 1.15.2-R0.1-SNAPSHOT
name: MC 1.15

on:
  push:
    branches: [ "main", "master", "dev" ]

jobs:
  test:
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 8
      minecraft-version: "1.15.2-R0.1-SNAPSHOT"