# 1.14.4-R0.1-SNAPSHOT
name: MC 1.14

on:
  push:
    branches: [ "main", "master", "dev" ]

jobs:
  test:
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 11
      minecraft-version: "1.14.4-R0.1-SNAPSHOT"