# 1.19.4-R0.1-SNAPSHOT
name: MC 1.19

on:
  workflow_run:
    workflows: [ "Execute tests with Gradle" ]
    types:
      - completed

jobs:
  test:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 8
      minecraft-version: "1.19.4-R0.1-SNAPSHOT"