# 1.8.8-R0.1-SNAPSHOT
name: MC 1.8

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 8
      minecraft-version: "1.8.8-R0.1-SNAPSHOT"