# 1.12.2-R0.1-SNAPSHOT
name: MC 1.12

on:
  workflow_run:
    workflows: [ "Execute tests with Gradle" ]
    types:
      - completed

concurrency:
  group: mc-1.12-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 8
      minecraft-version: "1.12.2-R0.1-SNAPSHOT"