# 1.17.1-R0.1-SNAPSHOT
name: MC 1.17

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    uses: ./.github/workflows/bukkit-test.yml
    with:
      java-version: 17
      minecraft-version: "1.17.1-R0.1-SNAPSHOT"