on:
  workflow_call:
    inputs:
      java-version: '8'
      minecraft-version: "1.12.2-R0.1-SNAPSHOT"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${ inputs.java-version }
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        env:
          MINECRAFT_VERSION: ${ inputs.minecraft-version }

      - name: Test with Gradle Wrapper
        run: ./gradlew test
        env:
          MINECRAFT_VERSION: ${ inputs.minecraft-version }
